### ISSUE TITLE
Removing buffs does not always remove their child effects

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#223]
Applying a buff to the character, then deleting that buff does not always delete the effects that belong to the buff, leaving orphaned effects in the character tree which still apply to the character, but can't be reached to be deleted.

**Comment by ThaumRystra** [comment]
fixed in #184

**Comment by DinoSage** [comment]
Buff was not removed! I added a buff for spell barkskin to make Armor min 16. It is now stuck like that. I deleted buff but is still there

**Comment by DinoSage** [comment]
Nevermind. I was being dumb and bad. Got it fixed.

**Comment by svidas01** [comment]
I added a buff that is a +1 to AC and all saving throws, and it is still showing up for me. I deleted the buff, deleted the spell, refreshed the page, completely closed and relaunched Chrome, and it's still there. Does it just take time for the website to refresh? Any help would be appreciated!
